version: '2'

services:

  db:
    image: postgres
    restart: always
    ports: 
      - '5431:5432'
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'weather_report'
    volumes:
      - ./database/sql/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql

  db_uploader:
    build: ./database
    depends_on:
      - db
    links:
      - db
    volumes:
     - ./database:/code

  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - db_uploader
    links:
      - db
    volumes:
     - ./app:/code
