version: '2'

services:

  db:
    image: postgres
    restart: always
    ports: 
      - '5431:5432'
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'homework'

  web:
    build: .
    ports:
      - "5000:5000"
    links:
      - db
    volumes:
     - .:/code
